// Code generated by mockery v2.53.5. DO NOT EDIT.

package services

import (
	context "context"
	time "time"

	domain "github.com/ravilock/sentir-mais-backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// mockWeeklySummaryFinder is an autogenerated mock type for the weeklySummaryFinder type
type mockWeeklySummaryFinder struct {
	mock.Mock
}

type mockWeeklySummaryFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *mockWeeklySummaryFinder) EXPECT() *mockWeeklySummaryFinder_Expecter {
	return &mockWeeklySummaryFinder_Expecter{mock: &_m.Mock}
}

// FindByUserAndWeek provides a mock function with given fields: ctx, userID, weekStart
func (_m *mockWeeklySummaryFinder) FindByUserAndWeek(ctx context.Context, userID string, weekStart time.Time) (domain.WeeklySummary, error) {
	ret := _m.Called(ctx, userID, weekStart)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserAndWeek")
	}

	var r0 domain.WeeklySummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) (domain.WeeklySummary, error)); ok {
		return rf(ctx, userID, weekStart)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) domain.WeeklySummary); ok {
		r0 = rf(ctx, userID, weekStart)
	} else {
		r0 = ret.Get(0).(domain.WeeklySummary)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = rf(ctx, userID, weekStart)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockWeeklySummaryFinder_FindByUserAndWeek_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserAndWeek'
type mockWeeklySummaryFinder_FindByUserAndWeek_Call struct {
	*mock.Call
}

// FindByUserAndWeek is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - weekStart time.Time
func (_e *mockWeeklySummaryFinder_Expecter) FindByUserAndWeek(ctx interface{}, userID interface{}, weekStart interface{}) *mockWeeklySummaryFinder_FindByUserAndWeek_Call {
	return &mockWeeklySummaryFinder_FindByUserAndWeek_Call{Call: _e.mock.On("FindByUserAndWeek", ctx, userID, weekStart)}
}

func (_c *mockWeeklySummaryFinder_FindByUserAndWeek_Call) Run(run func(ctx context.Context, userID string, weekStart time.Time)) *mockWeeklySummaryFinder_FindByUserAndWeek_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time))
	})
	return _c
}

func (_c *mockWeeklySummaryFinder_FindByUserAndWeek_Call) Return(_a0 domain.WeeklySummary, _a1 error) *mockWeeklySummaryFinder_FindByUserAndWeek_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockWeeklySummaryFinder_FindByUserAndWeek_Call) RunAndReturn(run func(context.Context, string, time.Time) (domain.WeeklySummary, error)) *mockWeeklySummaryFinder_FindByUserAndWeek_Call {
	_c.Call.Return(run)
	return _c
}

// newMockWeeklySummaryFinder creates a new instance of mockWeeklySummaryFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockWeeklySummaryFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockWeeklySummaryFinder {
	mock := &mockWeeklySummaryFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
