// Code generated by mockery v2.53.5. DO NOT EDIT.

package services

import (
	context "context"

	domain "github.com/ravilock/sentir-mais-backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// mockWeeklySummaryUpserter is an autogenerated mock type for the weeklySummaryUpserter type
type mockWeeklySummaryUpserter struct {
	mock.Mock
}

type mockWeeklySummaryUpserter_Expecter struct {
	mock *mock.Mock
}

func (_m *mockWeeklySummaryUpserter) EXPECT() *mockWeeklySummaryUpserter_Expecter {
	return &mockWeeklySummaryUpserter_Expecter{mock: &_m.Mock}
}

// Upsert provides a mock function with given fields: ctx, summary
func (_m *mockWeeklySummaryUpserter) Upsert(ctx context.Context, summary domain.WeeklySummary) error {
	ret := _m.Called(ctx, summary)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.WeeklySummary) error); ok {
		r0 = rf(ctx, summary)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockWeeklySummaryUpserter_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type mockWeeklySummaryUpserter_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - summary domain.WeeklySummary
func (_e *mockWeeklySummaryUpserter_Expecter) Upsert(ctx interface{}, summary interface{}) *mockWeeklySummaryUpserter_Upsert_Call {
	return &mockWeeklySummaryUpserter_Upsert_Call{Call: _e.mock.On("Upsert", ctx, summary)}
}

func (_c *mockWeeklySummaryUpserter_Upsert_Call) Run(run func(ctx context.Context, summary domain.WeeklySummary)) *mockWeeklySummaryUpserter_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.WeeklySummary))
	})
	return _c
}

func (_c *mockWeeklySummaryUpserter_Upsert_Call) Return(_a0 error) *mockWeeklySummaryUpserter_Upsert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockWeeklySummaryUpserter_Upsert_Call) RunAndReturn(run func(context.Context, domain.WeeklySummary) error) *mockWeeklySummaryUpserter_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// newMockWeeklySummaryUpserter creates a new instance of mockWeeklySummaryUpserter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockWeeklySummaryUpserter(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockWeeklySummaryUpserter {
	mock := &mockWeeklySummaryUpserter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
