// Code generated by mockery v2.53.5. DO NOT EDIT.

package services

import (
	context "context"
	time "time"

	domain "github.com/ravilock/sentir-mais-backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// mockDailySummaryRangeLister is an autogenerated mock type for the dailySummaryRangeLister type
type mockDailySummaryRangeLister struct {
	mock.Mock
}

type mockDailySummaryRangeLister_Expecter struct {
	mock *mock.Mock
}

func (_m *mockDailySummaryRangeLister) EXPECT() *mockDailySummaryRangeLister_Expecter {
	return &mockDailySummaryRangeLister_Expecter{mock: &_m.Mock}
}

// ListByUserAndDayRange provides a mock function with given fields: ctx, userID, from, to
func (_m *mockDailySummaryRangeLister) ListByUserAndDayRange(ctx context.Context, userID string, from time.Time, to time.Time) ([]domain.DailySummary, error) {
	ret := _m.Called(ctx, userID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for ListByUserAndDayRange")
	}

	var r0 []domain.DailySummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) ([]domain.DailySummary, error)); ok {
		return rf(ctx, userID, from, to)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) []domain.DailySummary); ok {
		r0 = rf(ctx, userID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.DailySummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time) error); ok {
		r1 = rf(ctx, userID, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockDailySummaryRangeLister_ListByUserAndDayRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUserAndDayRange'
type mockDailySummaryRangeLister_ListByUserAndDayRange_Call struct {
	*mock.Call
}

// ListByUserAndDayRange is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - from time.Time
//   - to time.Time
func (_e *mockDailySummaryRangeLister_Expecter) ListByUserAndDayRange(ctx interface{}, userID interface{}, from interface{}, to interface{}) *mockDailySummaryRangeLister_ListByUserAndDayRange_Call {
	return &mockDailySummaryRangeLister_ListByUserAndDayRange_Call{Call: _e.mock.On("ListByUserAndDayRange", ctx, userID, from, to)}
}

func (_c *mockDailySummaryRangeLister_ListByUserAndDayRange_Call) Run(run func(ctx context.Context, userID string, from time.Time, to time.Time)) *mockDailySummaryRangeLister_ListByUserAndDayRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *mockDailySummaryRangeLister_ListByUserAndDayRange_Call) Return(_a0 []domain.DailySummary, _a1 error) *mockDailySummaryRangeLister_ListByUserAndDayRange_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockDailySummaryRangeLister_ListByUserAndDayRange_Call) RunAndReturn(run func(context.Context, string, time.Time, time.Time) ([]domain.DailySummary, error)) *mockDailySummaryRangeLister_ListByUserAndDayRange_Call {
	_c.Call.Return(run)
	return _c
}

// newMockDailySummaryRangeLister creates a new instance of mockDailySummaryRangeLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockDailySummaryRangeLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockDailySummaryRangeLister {
	mock := &mockDailySummaryRangeLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
