// Code generated by mockery v2.53.5. DO NOT EDIT.

package services

import (
	context "context"
	time "time"

	domain "github.com/ravilock/sentir-mais-backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// mockAnalysisRangeLister is an autogenerated mock type for the analysisRangeLister type
type mockAnalysisRangeLister struct {
	mock.Mock
}

type mockAnalysisRangeLister_Expecter struct {
	mock *mock.Mock
}

func (_m *mockAnalysisRangeLister) EXPECT() *mockAnalysisRangeLister_Expecter {
	return &mockAnalysisRangeLister_Expecter{mock: &_m.Mock}
}

// ListByUserAndCreatedAtRange provides a mock function with given fields: ctx, userID, start, end
func (_m *mockAnalysisRangeLister) ListByUserAndCreatedAtRange(ctx context.Context, userID string, start time.Time, end time.Time) ([]domain.MessageAnalysis, error) {
	ret := _m.Called(ctx, userID, start, end)

	if len(ret) == 0 {
		panic("no return value specified for ListByUserAndCreatedAtRange")
	}

	var r0 []domain.MessageAnalysis
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) ([]domain.MessageAnalysis, error)); ok {
		return rf(ctx, userID, start, end)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) []domain.MessageAnalysis); ok {
		r0 = rf(ctx, userID, start, end)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.MessageAnalysis)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time) error); ok {
		r1 = rf(ctx, userID, start, end)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockAnalysisRangeLister_ListByUserAndCreatedAtRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUserAndCreatedAtRange'
type mockAnalysisRangeLister_ListByUserAndCreatedAtRange_Call struct {
	*mock.Call
}

// ListByUserAndCreatedAtRange is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - start time.Time
//   - end time.Time
func (_e *mockAnalysisRangeLister_Expecter) ListByUserAndCreatedAtRange(ctx interface{}, userID interface{}, start interface{}, end interface{}) *mockAnalysisRangeLister_ListByUserAndCreatedAtRange_Call {
	return &mockAnalysisRangeLister_ListByUserAndCreatedAtRange_Call{Call: _e.mock.On("ListByUserAndCreatedAtRange", ctx, userID, start, end)}
}

func (_c *mockAnalysisRangeLister_ListByUserAndCreatedAtRange_Call) Run(run func(ctx context.Context, userID string, start time.Time, end time.Time)) *mockAnalysisRangeLister_ListByUserAndCreatedAtRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *mockAnalysisRangeLister_ListByUserAndCreatedAtRange_Call) Return(_a0 []domain.MessageAnalysis, _a1 error) *mockAnalysisRangeLister_ListByUserAndCreatedAtRange_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockAnalysisRangeLister_ListByUserAndCreatedAtRange_Call) RunAndReturn(run func(context.Context, string, time.Time, time.Time) ([]domain.MessageAnalysis, error)) *mockAnalysisRangeLister_ListByUserAndCreatedAtRange_Call {
	_c.Call.Return(run)
	return _c
}

// newMockAnalysisRangeLister creates a new instance of mockAnalysisRangeLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockAnalysisRangeLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockAnalysisRangeLister {
	mock := &mockAnalysisRangeLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
