// Code generated by mockery v2.53.5. DO NOT EDIT.

package services

import (
	context "context"

	domain "github.com/ravilock/sentir-mais-backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// mockDailySummaryUpserter is an autogenerated mock type for the dailySummaryUpserter type
type mockDailySummaryUpserter struct {
	mock.Mock
}

type mockDailySummaryUpserter_Expecter struct {
	mock *mock.Mock
}

func (_m *mockDailySummaryUpserter) EXPECT() *mockDailySummaryUpserter_Expecter {
	return &mockDailySummaryUpserter_Expecter{mock: &_m.Mock}
}

// Upsert provides a mock function with given fields: ctx, summary
func (_m *mockDailySummaryUpserter) Upsert(ctx context.Context, summary domain.DailySummary) error {
	ret := _m.Called(ctx, summary)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.DailySummary) error); ok {
		r0 = rf(ctx, summary)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockDailySummaryUpserter_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type mockDailySummaryUpserter_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - summary domain.DailySummary
func (_e *mockDailySummaryUpserter_Expecter) Upsert(ctx interface{}, summary interface{}) *mockDailySummaryUpserter_Upsert_Call {
	return &mockDailySummaryUpserter_Upsert_Call{Call: _e.mock.On("Upsert", ctx, summary)}
}

func (_c *mockDailySummaryUpserter_Upsert_Call) Run(run func(ctx context.Context, summary domain.DailySummary)) *mockDailySummaryUpserter_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.DailySummary))
	})
	return _c
}

func (_c *mockDailySummaryUpserter_Upsert_Call) Return(_a0 error) *mockDailySummaryUpserter_Upsert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockDailySummaryUpserter_Upsert_Call) RunAndReturn(run func(context.Context, domain.DailySummary) error) *mockDailySummaryUpserter_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// newMockDailySummaryUpserter creates a new instance of mockDailySummaryUpserter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockDailySummaryUpserter(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockDailySummaryUpserter {
	mock := &mockDailySummaryUpserter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
