// Code generated by mockery v2.53.5. DO NOT EDIT.

package services

import (
	context "context"

	domain "github.com/ravilock/sentir-mais-backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockFeelingClassifier is an autogenerated mock type for the FeelingClassifier type
type MockFeelingClassifier struct {
	mock.Mock
}

type MockFeelingClassifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFeelingClassifier) EXPECT() *MockFeelingClassifier_Expecter {
	return &MockFeelingClassifier_Expecter{mock: &_m.Mock}
}

// Classify provides a mock function with given fields: ctx, text
func (_m *MockFeelingClassifier) Classify(ctx context.Context, text string) (domain.ClassificationResult, error) {
	ret := _m.Called(ctx, text)

	if len(ret) == 0 {
		panic("no return value specified for Classify")
	}

	var r0 domain.ClassificationResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.ClassificationResult, error)); ok {
		return rf(ctx, text)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.ClassificationResult); ok {
		r0 = rf(ctx, text)
	} else {
		r0 = ret.Get(0).(domain.ClassificationResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, text)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFeelingClassifier_Classify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Classify'
type MockFeelingClassifier_Classify_Call struct {
	*mock.Call
}

// Classify is a helper method to define mock.On call
//   - ctx context.Context
//   - text string
func (_e *MockFeelingClassifier_Expecter) Classify(ctx interface{}, text interface{}) *MockFeelingClassifier_Classify_Call {
	return &MockFeelingClassifier_Classify_Call{Call: _e.mock.On("Classify", ctx, text)}
}

func (_c *MockFeelingClassifier_Classify_Call) Run(run func(ctx context.Context, text string)) *MockFeelingClassifier_Classify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockFeelingClassifier_Classify_Call) Return(_a0 domain.ClassificationResult, _a1 error) *MockFeelingClassifier_Classify_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFeelingClassifier_Classify_Call) RunAndReturn(run func(context.Context, string) (domain.ClassificationResult, error)) *MockFeelingClassifier_Classify_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFeelingClassifier creates a new instance of MockFeelingClassifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFeelingClassifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFeelingClassifier {
	mock := &MockFeelingClassifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
