// Code generated by mockery v2.53.5. DO NOT EDIT.

package services

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockMessageAnalysisFinder is an autogenerated mock type for the MessageAnalysisFinder type
type MockMessageAnalysisFinder struct {
	mock.Mock
}

type MockMessageAnalysisFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessageAnalysisFinder) EXPECT() *MockMessageAnalysisFinder_Expecter {
	return &MockMessageAnalysisFinder_Expecter{mock: &_m.Mock}
}

// ExistsByMessageID provides a mock function with given fields: ctx, messageID
func (_m *MockMessageAnalysisFinder) ExistsByMessageID(ctx context.Context, messageID string) (bool, error) {
	ret := _m.Called(ctx, messageID)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByMessageID")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, messageID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, messageID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, messageID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMessageAnalysisFinder_ExistsByMessageID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByMessageID'
type MockMessageAnalysisFinder_ExistsByMessageID_Call struct {
	*mock.Call
}

// ExistsByMessageID is a helper method to define mock.On call
//   - ctx context.Context
//   - messageID string
func (_e *MockMessageAnalysisFinder_Expecter) ExistsByMessageID(ctx interface{}, messageID interface{}) *MockMessageAnalysisFinder_ExistsByMessageID_Call {
	return &MockMessageAnalysisFinder_ExistsByMessageID_Call{Call: _e.mock.On("ExistsByMessageID", ctx, messageID)}
}

func (_c *MockMessageAnalysisFinder_ExistsByMessageID_Call) Run(run func(ctx context.Context, messageID string)) *MockMessageAnalysisFinder_ExistsByMessageID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMessageAnalysisFinder_ExistsByMessageID_Call) Return(_a0 bool, _a1 error) *MockMessageAnalysisFinder_ExistsByMessageID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMessageAnalysisFinder_ExistsByMessageID_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockMessageAnalysisFinder_ExistsByMessageID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMessageAnalysisFinder creates a new instance of MockMessageAnalysisFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessageAnalysisFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessageAnalysisFinder {
	mock := &MockMessageAnalysisFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
