// Code generated by mockery v2.53.5. DO NOT EDIT.

package services

import (
	context "context"

	domain "github.com/ravilock/sentir-mais-backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockMessageAnalysisCreator is an autogenerated mock type for the MessageAnalysisCreator type
type MockMessageAnalysisCreator struct {
	mock.Mock
}

type MockMessageAnalysisCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessageAnalysisCreator) EXPECT() *MockMessageAnalysisCreator_Expecter {
	return &MockMessageAnalysisCreator_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, analysis
func (_m *MockMessageAnalysisCreator) Create(ctx context.Context, analysis domain.MessageAnalysis) error {
	ret := _m.Called(ctx, analysis)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.MessageAnalysis) error); ok {
		r0 = rf(ctx, analysis)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMessageAnalysisCreator_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockMessageAnalysisCreator_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - analysis domain.MessageAnalysis
func (_e *MockMessageAnalysisCreator_Expecter) Create(ctx interface{}, analysis interface{}) *MockMessageAnalysisCreator_Create_Call {
	return &MockMessageAnalysisCreator_Create_Call{Call: _e.mock.On("Create", ctx, analysis)}
}

func (_c *MockMessageAnalysisCreator_Create_Call) Run(run func(ctx context.Context, analysis domain.MessageAnalysis)) *MockMessageAnalysisCreator_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.MessageAnalysis))
	})
	return _c
}

func (_c *MockMessageAnalysisCreator_Create_Call) Return(_a0 error) *MockMessageAnalysisCreator_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMessageAnalysisCreator_Create_Call) RunAndReturn(run func(context.Context, domain.MessageAnalysis) error) *MockMessageAnalysisCreator_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMessageAnalysisCreator creates a new instance of MockMessageAnalysisCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessageAnalysisCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessageAnalysisCreator {
	mock := &MockMessageAnalysisCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
