// Code generated by mockery v2.53.5. DO NOT EDIT.

package services

import (
	context "context"

	domain "github.com/ravilock/sentir-mais-backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// mockChatLister is an autogenerated mock type for the chatLister type
type mockChatLister struct {
	mock.Mock
}

type mockChatLister_Expecter struct {
	mock *mock.Mock
}

func (_m *mockChatLister) EXPECT() *mockChatLister_Expecter {
	return &mockChatLister_Expecter{mock: &_m.Mock}
}

// ListByUserID provides a mock function with given fields: ctx, userID
func (_m *mockChatLister) ListByUserID(ctx context.Context, userID string) ([]domain.Chat, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUserID")
	}

	var r0 []domain.Chat
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.Chat, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.Chat); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Chat)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockChatLister_ListByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUserID'
type mockChatLister_ListByUserID_Call struct {
	*mock.Call
}

// ListByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *mockChatLister_Expecter) ListByUserID(ctx interface{}, userID interface{}) *mockChatLister_ListByUserID_Call {
	return &mockChatLister_ListByUserID_Call{Call: _e.mock.On("ListByUserID", ctx, userID)}
}

func (_c *mockChatLister_ListByUserID_Call) Run(run func(ctx context.Context, userID string)) *mockChatLister_ListByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *mockChatLister_ListByUserID_Call) Return(_a0 []domain.Chat, _a1 error) *mockChatLister_ListByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockChatLister_ListByUserID_Call) RunAndReturn(run func(context.Context, string) ([]domain.Chat, error)) *mockChatLister_ListByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// newMockChatLister creates a new instance of mockChatLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockChatLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockChatLister {
	mock := &mockChatLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
