// Code generated by mockery v2.53.5. DO NOT EDIT.

package services

import (
	context "context"

	domain "github.com/ravilock/sentir-mais-backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// mockChatFinder is an autogenerated mock type for the chatFinder type
type mockChatFinder struct {
	mock.Mock
}

type mockChatFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *mockChatFinder) EXPECT() *mockChatFinder_Expecter {
	return &mockChatFinder_Expecter{mock: &_m.Mock}
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *mockChatFinder) FindByID(ctx context.Context, id string) (domain.Chat, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 domain.Chat
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Chat, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Chat); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Chat)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockChatFinder_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type mockChatFinder_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *mockChatFinder_Expecter) FindByID(ctx interface{}, id interface{}) *mockChatFinder_FindByID_Call {
	return &mockChatFinder_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *mockChatFinder_FindByID_Call) Run(run func(ctx context.Context, id string)) *mockChatFinder_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *mockChatFinder_FindByID_Call) Return(_a0 domain.Chat, _a1 error) *mockChatFinder_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockChatFinder_FindByID_Call) RunAndReturn(run func(context.Context, string) (domain.Chat, error)) *mockChatFinder_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// newMockChatFinder creates a new instance of mockChatFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockChatFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockChatFinder {
	mock := &mockChatFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
