// Code generated by mockery v2.53.5. DO NOT EDIT.

package services

import (
	context "context"

	domain "github.com/ravilock/sentir-mais-backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// mockSummaryWriter is an autogenerated mock type for the summaryWriter type
type mockSummaryWriter struct {
	mock.Mock
}

type mockSummaryWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *mockSummaryWriter) EXPECT() *mockSummaryWriter_Expecter {
	return &mockSummaryWriter_Expecter{mock: &_m.Mock}
}

// UpdateForAnalysis provides a mock function with given fields: ctx, analysis
func (_m *mockSummaryWriter) UpdateForAnalysis(ctx context.Context, analysis domain.MessageAnalysis) error {
	ret := _m.Called(ctx, analysis)

	if len(ret) == 0 {
		panic("no return value specified for UpdateForAnalysis")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.MessageAnalysis) error); ok {
		r0 = rf(ctx, analysis)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockSummaryWriter_UpdateForAnalysis_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateForAnalysis'
type mockSummaryWriter_UpdateForAnalysis_Call struct {
	*mock.Call
}

// UpdateForAnalysis is a helper method to define mock.On call
//   - ctx context.Context
//   - analysis domain.MessageAnalysis
func (_e *mockSummaryWriter_Expecter) UpdateForAnalysis(ctx interface{}, analysis interface{}) *mockSummaryWriter_UpdateForAnalysis_Call {
	return &mockSummaryWriter_UpdateForAnalysis_Call{Call: _e.mock.On("UpdateForAnalysis", ctx, analysis)}
}

func (_c *mockSummaryWriter_UpdateForAnalysis_Call) Run(run func(ctx context.Context, analysis domain.MessageAnalysis)) *mockSummaryWriter_UpdateForAnalysis_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.MessageAnalysis))
	})
	return _c
}

func (_c *mockSummaryWriter_UpdateForAnalysis_Call) Return(_a0 error) *mockSummaryWriter_UpdateForAnalysis_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockSummaryWriter_UpdateForAnalysis_Call) RunAndReturn(run func(context.Context, domain.MessageAnalysis) error) *mockSummaryWriter_UpdateForAnalysis_Call {
	_c.Call.Return(run)
	return _c
}

// newMockSummaryWriter creates a new instance of mockSummaryWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockSummaryWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockSummaryWriter {
	mock := &mockSummaryWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
