// Code generated by mockery v2.53.5. DO NOT EDIT.

package services

import (
	context "context"

	queue "github.com/ravilock/sentir-mais-backend/internal/analysis/queue"
	mock "github.com/stretchr/testify/mock"
)

// mockAnalysisJobEnqueuer is an autogenerated mock type for the analysisJobEnqueuer type
type mockAnalysisJobEnqueuer struct {
	mock.Mock
}

type mockAnalysisJobEnqueuer_Expecter struct {
	mock *mock.Mock
}

func (_m *mockAnalysisJobEnqueuer) EXPECT() *mockAnalysisJobEnqueuer_Expecter {
	return &mockAnalysisJobEnqueuer_Expecter{mock: &_m.Mock}
}

// Enqueue provides a mock function with given fields: ctx, job
func (_m *mockAnalysisJobEnqueuer) Enqueue(ctx context.Context, job queue.AnalysisJob) error {
	ret := _m.Called(ctx, job)

	if len(ret) == 0 {
		panic("no return value specified for Enqueue")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, queue.AnalysisJob) error); ok {
		r0 = rf(ctx, job)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockAnalysisJobEnqueuer_Enqueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enqueue'
type mockAnalysisJobEnqueuer_Enqueue_Call struct {
	*mock.Call
}

// Enqueue is a helper method to define mock.On call
//   - ctx context.Context
//   - job queue.AnalysisJob
func (_e *mockAnalysisJobEnqueuer_Expecter) Enqueue(ctx interface{}, job interface{}) *mockAnalysisJobEnqueuer_Enqueue_Call {
	return &mockAnalysisJobEnqueuer_Enqueue_Call{Call: _e.mock.On("Enqueue", ctx, job)}
}

func (_c *mockAnalysisJobEnqueuer_Enqueue_Call) Run(run func(ctx context.Context, job queue.AnalysisJob)) *mockAnalysisJobEnqueuer_Enqueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(queue.AnalysisJob))
	})
	return _c
}

func (_c *mockAnalysisJobEnqueuer_Enqueue_Call) Return(_a0 error) *mockAnalysisJobEnqueuer_Enqueue_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockAnalysisJobEnqueuer_Enqueue_Call) RunAndReturn(run func(context.Context, queue.AnalysisJob) error) *mockAnalysisJobEnqueuer_Enqueue_Call {
	_c.Call.Return(run)
	return _c
}

// newMockAnalysisJobEnqueuer creates a new instance of mockAnalysisJobEnqueuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockAnalysisJobEnqueuer(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockAnalysisJobEnqueuer {
	mock := &mockAnalysisJobEnqueuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
