// Code generated by mockery v2.53.5. DO NOT EDIT.

package services

import (
	context "context"

	domain "github.com/ravilock/sentir-mais-backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// mockChatCreator is an autogenerated mock type for the chatCreator type
type mockChatCreator struct {
	mock.Mock
}

type mockChatCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *mockChatCreator) EXPECT() *mockChatCreator_Expecter {
	return &mockChatCreator_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, chat
func (_m *mockChatCreator) Create(ctx context.Context, chat domain.Chat) error {
	ret := _m.Called(ctx, chat)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Chat) error); ok {
		r0 = rf(ctx, chat)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockChatCreator_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type mockChatCreator_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - chat domain.Chat
func (_e *mockChatCreator_Expecter) Create(ctx interface{}, chat interface{}) *mockChatCreator_Create_Call {
	return &mockChatCreator_Create_Call{Call: _e.mock.On("Create", ctx, chat)}
}

func (_c *mockChatCreator_Create_Call) Run(run func(ctx context.Context, chat domain.Chat)) *mockChatCreator_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Chat))
	})
	return _c
}

func (_c *mockChatCreator_Create_Call) Return(_a0 error) *mockChatCreator_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockChatCreator_Create_Call) RunAndReturn(run func(context.Context, domain.Chat) error) *mockChatCreator_Create_Call {
	_c.Call.Return(run)
	return _c
}

// newMockChatCreator creates a new instance of mockChatCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockChatCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockChatCreator {
	mock := &mockChatCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
