// Code generated by mockery v2.53.5. DO NOT EDIT.

package services

import (
	context "context"

	domain "github.com/ravilock/sentir-mais-backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// mockMessageCreator is an autogenerated mock type for the messageCreator type
type mockMessageCreator struct {
	mock.Mock
}

type mockMessageCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *mockMessageCreator) EXPECT() *mockMessageCreator_Expecter {
	return &mockMessageCreator_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, message
func (_m *mockMessageCreator) Create(ctx context.Context, message domain.Message) error {
	ret := _m.Called(ctx, message)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Message) error); ok {
		r0 = rf(ctx, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockMessageCreator_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type mockMessageCreator_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - message domain.Message
func (_e *mockMessageCreator_Expecter) Create(ctx interface{}, message interface{}) *mockMessageCreator_Create_Call {
	return &mockMessageCreator_Create_Call{Call: _e.mock.On("Create", ctx, message)}
}

func (_c *mockMessageCreator_Create_Call) Run(run func(ctx context.Context, message domain.Message)) *mockMessageCreator_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Message))
	})
	return _c
}

func (_c *mockMessageCreator_Create_Call) Return(_a0 error) *mockMessageCreator_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockMessageCreator_Create_Call) RunAndReturn(run func(context.Context, domain.Message) error) *mockMessageCreator_Create_Call {
	_c.Call.Return(run)
	return _c
}

// newMockMessageCreator creates a new instance of mockMessageCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockMessageCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockMessageCreator {
	mock := &mockMessageCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
