// Code generated by mockery v2.53.5. DO NOT EDIT.

package services

import (
	context "context"

	domain "github.com/ravilock/sentir-mais-backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// mockMessageLister is an autogenerated mock type for the messageLister type
type mockMessageLister struct {
	mock.Mock
}

type mockMessageLister_Expecter struct {
	mock *mock.Mock
}

func (_m *mockMessageLister) EXPECT() *mockMessageLister_Expecter {
	return &mockMessageLister_Expecter{mock: &_m.Mock}
}

// ListByChatID provides a mock function with given fields: ctx, chatID
func (_m *mockMessageLister) ListByChatID(ctx context.Context, chatID string) ([]domain.Message, error) {
	ret := _m.Called(ctx, chatID)

	if len(ret) == 0 {
		panic("no return value specified for ListByChatID")
	}

	var r0 []domain.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.Message, error)); ok {
		return rf(ctx, chatID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.Message); ok {
		r0 = rf(ctx, chatID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, chatID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockMessageLister_ListByChatID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByChatID'
type mockMessageLister_ListByChatID_Call struct {
	*mock.Call
}

// ListByChatID is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID string
func (_e *mockMessageLister_Expecter) ListByChatID(ctx interface{}, chatID interface{}) *mockMessageLister_ListByChatID_Call {
	return &mockMessageLister_ListByChatID_Call{Call: _e.mock.On("ListByChatID", ctx, chatID)}
}

func (_c *mockMessageLister_ListByChatID_Call) Run(run func(ctx context.Context, chatID string)) *mockMessageLister_ListByChatID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *mockMessageLister_ListByChatID_Call) Return(_a0 []domain.Message, _a1 error) *mockMessageLister_ListByChatID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockMessageLister_ListByChatID_Call) RunAndReturn(run func(context.Context, string) ([]domain.Message, error)) *mockMessageLister_ListByChatID_Call {
	_c.Call.Return(run)
	return _c
}

// newMockMessageLister creates a new instance of mockMessageLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockMessageLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockMessageLister {
	mock := &mockMessageLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
