// Code generated by mockery v2.53.5. DO NOT EDIT.

package services

import (
	context "context"

	domain "github.com/ravilock/sentir-mais-backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// mockChatUpdater is an autogenerated mock type for the chatUpdater type
type mockChatUpdater struct {
	mock.Mock
}

type mockChatUpdater_Expecter struct {
	mock *mock.Mock
}

func (_m *mockChatUpdater) EXPECT() *mockChatUpdater_Expecter {
	return &mockChatUpdater_Expecter{mock: &_m.Mock}
}

// Update provides a mock function with given fields: ctx, chat
func (_m *mockChatUpdater) Update(ctx context.Context, chat domain.Chat) error {
	ret := _m.Called(ctx, chat)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Chat) error); ok {
		r0 = rf(ctx, chat)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockChatUpdater_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type mockChatUpdater_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - chat domain.Chat
func (_e *mockChatUpdater_Expecter) Update(ctx interface{}, chat interface{}) *mockChatUpdater_Update_Call {
	return &mockChatUpdater_Update_Call{Call: _e.mock.On("Update", ctx, chat)}
}

func (_c *mockChatUpdater_Update_Call) Run(run func(ctx context.Context, chat domain.Chat)) *mockChatUpdater_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Chat))
	})
	return _c
}

func (_c *mockChatUpdater_Update_Call) Return(_a0 error) *mockChatUpdater_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockChatUpdater_Update_Call) RunAndReturn(run func(context.Context, domain.Chat) error) *mockChatUpdater_Update_Call {
	_c.Call.Return(run)
	return _c
}

// newMockChatUpdater creates a new instance of mockChatUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockChatUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockChatUpdater {
	mock := &mockChatUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
