// Code generated by mockery v2.53.5. DO NOT EDIT.

package services

import (
	context "context"

	domain "github.com/ravilock/sentir-mais-backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// mockLatestMessageFinder is an autogenerated mock type for the latestMessageFinder type
type mockLatestMessageFinder struct {
	mock.Mock
}

type mockLatestMessageFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *mockLatestMessageFinder) EXPECT() *mockLatestMessageFinder_Expecter {
	return &mockLatestMessageFinder_Expecter{mock: &_m.Mock}
}

// FindLatestByChatID provides a mock function with given fields: ctx, chatID
func (_m *mockLatestMessageFinder) FindLatestByChatID(ctx context.Context, chatID string) (domain.Message, error) {
	ret := _m.Called(ctx, chatID)

	if len(ret) == 0 {
		panic("no return value specified for FindLatestByChatID")
	}

	var r0 domain.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Message, error)); ok {
		return rf(ctx, chatID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Message); ok {
		r0 = rf(ctx, chatID)
	} else {
		r0 = ret.Get(0).(domain.Message)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, chatID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockLatestMessageFinder_FindLatestByChatID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindLatestByChatID'
type mockLatestMessageFinder_FindLatestByChatID_Call struct {
	*mock.Call
}

// FindLatestByChatID is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID string
func (_e *mockLatestMessageFinder_Expecter) FindLatestByChatID(ctx interface{}, chatID interface{}) *mockLatestMessageFinder_FindLatestByChatID_Call {
	return &mockLatestMessageFinder_FindLatestByChatID_Call{Call: _e.mock.On("FindLatestByChatID", ctx, chatID)}
}

func (_c *mockLatestMessageFinder_FindLatestByChatID_Call) Run(run func(ctx context.Context, chatID string)) *mockLatestMessageFinder_FindLatestByChatID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *mockLatestMessageFinder_FindLatestByChatID_Call) Return(_a0 domain.Message, _a1 error) *mockLatestMessageFinder_FindLatestByChatID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockLatestMessageFinder_FindLatestByChatID_Call) RunAndReturn(run func(context.Context, string) (domain.Message, error)) *mockLatestMessageFinder_FindLatestByChatID_Call {
	_c.Call.Return(run)
	return _c
}

// newMockLatestMessageFinder creates a new instance of mockLatestMessageFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockLatestMessageFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockLatestMessageFinder {
	mock := &mockLatestMessageFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
