// Code generated by mockery v2.53.5. DO NOT EDIT.

package worker

import (
	context "context"
	time "time"

	queue "github.com/ravilock/sentir-mais-backend/internal/analysis/queue"
	mock "github.com/stretchr/testify/mock"
)

// MockQueue is an autogenerated mock type for the Queue type
type MockQueue struct {
	mock.Mock
}

type MockQueue_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueue) EXPECT() *MockQueue_Expecter {
	return &MockQueue_Expecter{mock: &_m.Mock}
}

// Ack provides a mock function with given fields: ctx, consumed
func (_m *MockQueue) Ack(ctx context.Context, consumed queue.ConsumedJob) error {
	ret := _m.Called(ctx, consumed)

	if len(ret) == 0 {
		panic("no return value specified for Ack")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, queue.ConsumedJob) error); ok {
		r0 = rf(ctx, consumed)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQueue_Ack_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ack'
type MockQueue_Ack_Call struct {
	*mock.Call
}

// Ack is a helper method to define mock.On call
//   - ctx context.Context
//   - consumed queue.ConsumedJob
func (_e *MockQueue_Expecter) Ack(ctx interface{}, consumed interface{}) *MockQueue_Ack_Call {
	return &MockQueue_Ack_Call{Call: _e.mock.On("Ack", ctx, consumed)}
}

func (_c *MockQueue_Ack_Call) Run(run func(ctx context.Context, consumed queue.ConsumedJob)) *MockQueue_Ack_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(queue.ConsumedJob))
	})
	return _c
}

func (_c *MockQueue_Ack_Call) Return(_a0 error) *MockQueue_Ack_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQueue_Ack_Call) RunAndReturn(run func(context.Context, queue.ConsumedJob) error) *MockQueue_Ack_Call {
	_c.Call.Return(run)
	return _c
}

// Consume provides a mock function with given fields: ctx, timeout
func (_m *MockQueue) Consume(ctx context.Context, timeout time.Duration) (queue.ConsumedJob, error) {
	ret := _m.Called(ctx, timeout)

	if len(ret) == 0 {
		panic("no return value specified for Consume")
	}

	var r0 queue.ConsumedJob
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Duration) (queue.ConsumedJob, error)); ok {
		return rf(ctx, timeout)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Duration) queue.ConsumedJob); ok {
		r0 = rf(ctx, timeout)
	} else {
		r0 = ret.Get(0).(queue.ConsumedJob)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Duration) error); ok {
		r1 = rf(ctx, timeout)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQueue_Consume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Consume'
type MockQueue_Consume_Call struct {
	*mock.Call
}

// Consume is a helper method to define mock.On call
//   - ctx context.Context
//   - timeout time.Duration
func (_e *MockQueue_Expecter) Consume(ctx interface{}, timeout interface{}) *MockQueue_Consume_Call {
	return &MockQueue_Consume_Call{Call: _e.mock.On("Consume", ctx, timeout)}
}

func (_c *MockQueue_Consume_Call) Run(run func(ctx context.Context, timeout time.Duration)) *MockQueue_Consume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Duration))
	})
	return _c
}

func (_c *MockQueue_Consume_Call) Return(_a0 queue.ConsumedJob, _a1 error) *MockQueue_Consume_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQueue_Consume_Call) RunAndReturn(run func(context.Context, time.Duration) (queue.ConsumedJob, error)) *MockQueue_Consume_Call {
	_c.Call.Return(run)
	return _c
}

// MoveDueRetries provides a mock function with given fields: ctx, now, limit
func (_m *MockQueue) MoveDueRetries(ctx context.Context, now time.Time, limit int64) (int64, error) {
	ret := _m.Called(ctx, now, limit)

	if len(ret) == 0 {
		panic("no return value specified for MoveDueRetries")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, int64) (int64, error)); ok {
		return rf(ctx, now, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, int64) int64); ok {
		r0 = rf(ctx, now, limit)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, int64) error); ok {
		r1 = rf(ctx, now, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQueue_MoveDueRetries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MoveDueRetries'
type MockQueue_MoveDueRetries_Call struct {
	*mock.Call
}

// MoveDueRetries is a helper method to define mock.On call
//   - ctx context.Context
//   - now time.Time
//   - limit int64
func (_e *MockQueue_Expecter) MoveDueRetries(ctx interface{}, now interface{}, limit interface{}) *MockQueue_MoveDueRetries_Call {
	return &MockQueue_MoveDueRetries_Call{Call: _e.mock.On("MoveDueRetries", ctx, now, limit)}
}

func (_c *MockQueue_MoveDueRetries_Call) Run(run func(ctx context.Context, now time.Time, limit int64)) *MockQueue_MoveDueRetries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time), args[2].(int64))
	})
	return _c
}

func (_c *MockQueue_MoveDueRetries_Call) Return(_a0 int64, _a1 error) *MockQueue_MoveDueRetries_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQueue_MoveDueRetries_Call) RunAndReturn(run func(context.Context, time.Time, int64) (int64, error)) *MockQueue_MoveDueRetries_Call {
	_c.Call.Return(run)
	return _c
}

// RetryLater provides a mock function with given fields: ctx, consumed, runAt
func (_m *MockQueue) RetryLater(ctx context.Context, consumed queue.ConsumedJob, runAt time.Time) error {
	ret := _m.Called(ctx, consumed, runAt)

	if len(ret) == 0 {
		panic("no return value specified for RetryLater")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, queue.ConsumedJob, time.Time) error); ok {
		r0 = rf(ctx, consumed, runAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQueue_RetryLater_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetryLater'
type MockQueue_RetryLater_Call struct {
	*mock.Call
}

// RetryLater is a helper method to define mock.On call
//   - ctx context.Context
//   - consumed queue.ConsumedJob
//   - runAt time.Time
func (_e *MockQueue_Expecter) RetryLater(ctx interface{}, consumed interface{}, runAt interface{}) *MockQueue_RetryLater_Call {
	return &MockQueue_RetryLater_Call{Call: _e.mock.On("RetryLater", ctx, consumed, runAt)}
}

func (_c *MockQueue_RetryLater_Call) Run(run func(ctx context.Context, consumed queue.ConsumedJob, runAt time.Time)) *MockQueue_RetryLater_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(queue.ConsumedJob), args[2].(time.Time))
	})
	return _c
}

func (_c *MockQueue_RetryLater_Call) Return(_a0 error) *MockQueue_RetryLater_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQueue_RetryLater_Call) RunAndReturn(run func(context.Context, queue.ConsumedJob, time.Time) error) *MockQueue_RetryLater_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQueue creates a new instance of MockQueue. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueue(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueue {
	mock := &MockQueue{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
