// Code generated by mockery v2.53.5. DO NOT EDIT.

package worker

import (
	context "context"

	domain "github.com/ravilock/sentir-mais-backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockDeadLetterCreator is an autogenerated mock type for the DeadLetterCreator type
type MockDeadLetterCreator struct {
	mock.Mock
}

type MockDeadLetterCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeadLetterCreator) EXPECT() *MockDeadLetterCreator_Expecter {
	return &MockDeadLetterCreator_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, deadLetter
func (_m *MockDeadLetterCreator) Create(ctx context.Context, deadLetter domain.AnalysisDeadLetter) error {
	ret := _m.Called(ctx, deadLetter)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.AnalysisDeadLetter) error); ok {
		r0 = rf(ctx, deadLetter)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDeadLetterCreator_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockDeadLetterCreator_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - deadLetter domain.AnalysisDeadLetter
func (_e *MockDeadLetterCreator_Expecter) Create(ctx interface{}, deadLetter interface{}) *MockDeadLetterCreator_Create_Call {
	return &MockDeadLetterCreator_Create_Call{Call: _e.mock.On("Create", ctx, deadLetter)}
}

func (_c *MockDeadLetterCreator_Create_Call) Run(run func(ctx context.Context, deadLetter domain.AnalysisDeadLetter)) *MockDeadLetterCreator_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.AnalysisDeadLetter))
	})
	return _c
}

func (_c *MockDeadLetterCreator_Create_Call) Return(_a0 error) *MockDeadLetterCreator_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDeadLetterCreator_Create_Call) RunAndReturn(run func(context.Context, domain.AnalysisDeadLetter) error) *MockDeadLetterCreator_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDeadLetterCreator creates a new instance of MockDeadLetterCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeadLetterCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeadLetterCreator {
	mock := &MockDeadLetterCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
