// Code generated by mockery v2.53.5. DO NOT EDIT.

package worker

import (
	context "context"

	queue "github.com/ravilock/sentir-mais-backend/internal/analysis/queue"
	mock "github.com/stretchr/testify/mock"
)

// MockProcessor is an autogenerated mock type for the Processor type
type MockProcessor struct {
	mock.Mock
}

type MockProcessor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProcessor) EXPECT() *MockProcessor_Expecter {
	return &MockProcessor_Expecter{mock: &_m.Mock}
}

// Process provides a mock function with given fields: ctx, job
func (_m *MockProcessor) Process(ctx context.Context, job queue.AnalysisJob) error {
	ret := _m.Called(ctx, job)

	if len(ret) == 0 {
		panic("no return value specified for Process")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, queue.AnalysisJob) error); ok {
		r0 = rf(ctx, job)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProcessor_Process_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Process'
type MockProcessor_Process_Call struct {
	*mock.Call
}

// Process is a helper method to define mock.On call
//   - ctx context.Context
//   - job queue.AnalysisJob
func (_e *MockProcessor_Expecter) Process(ctx interface{}, job interface{}) *MockProcessor_Process_Call {
	return &MockProcessor_Process_Call{Call: _e.mock.On("Process", ctx, job)}
}

func (_c *MockProcessor_Process_Call) Run(run func(ctx context.Context, job queue.AnalysisJob)) *MockProcessor_Process_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(queue.AnalysisJob))
	})
	return _c
}

func (_c *MockProcessor_Process_Call) Return(_a0 error) *MockProcessor_Process_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProcessor_Process_Call) RunAndReturn(run func(context.Context, queue.AnalysisJob) error) *MockProcessor_Process_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProcessor creates a new instance of MockProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProcessor {
	mock := &MockProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
