// Code generated by mockery v2.53.5. DO NOT EDIT.

package handlers

import (
	context "context"

	domain "github.com/ravilock/sentir-mais-backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// mockChatCreator is an autogenerated mock type for the chatCreator type
type mockChatCreator struct {
	mock.Mock
}

type mockChatCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *mockChatCreator) EXPECT() *mockChatCreator_Expecter {
	return &mockChatCreator_Expecter{mock: &_m.Mock}
}

// CreateChat provides a mock function with given fields: ctx, userID, initialMessage
func (_m *mockChatCreator) CreateChat(ctx context.Context, userID string, initialMessage string) (domain.Chat, domain.Message, error) {
	ret := _m.Called(ctx, userID, initialMessage)

	if len(ret) == 0 {
		panic("no return value specified for CreateChat")
	}

	var r0 domain.Chat
	var r1 domain.Message
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (domain.Chat, domain.Message, error)); ok {
		return rf(ctx, userID, initialMessage)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) domain.Chat); ok {
		r0 = rf(ctx, userID, initialMessage)
	} else {
		r0 = ret.Get(0).(domain.Chat)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) domain.Message); ok {
		r1 = rf(ctx, userID, initialMessage)
	} else {
		r1 = ret.Get(1).(domain.Message)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = rf(ctx, userID, initialMessage)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// mockChatCreator_CreateChat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateChat'
type mockChatCreator_CreateChat_Call struct {
	*mock.Call
}

// CreateChat is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - initialMessage string
func (_e *mockChatCreator_Expecter) CreateChat(ctx interface{}, userID interface{}, initialMessage interface{}) *mockChatCreator_CreateChat_Call {
	return &mockChatCreator_CreateChat_Call{Call: _e.mock.On("CreateChat", ctx, userID, initialMessage)}
}

func (_c *mockChatCreator_CreateChat_Call) Run(run func(ctx context.Context, userID string, initialMessage string)) *mockChatCreator_CreateChat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *mockChatCreator_CreateChat_Call) Return(_a0 domain.Chat, _a1 domain.Message, _a2 error) *mockChatCreator_CreateChat_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *mockChatCreator_CreateChat_Call) RunAndReturn(run func(context.Context, string, string) (domain.Chat, domain.Message, error)) *mockChatCreator_CreateChat_Call {
	_c.Call.Return(run)
	return _c
}

// newMockChatCreator creates a new instance of mockChatCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockChatCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockChatCreator {
	mock := &mockChatCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
