// Code generated by mockery v2.53.5. DO NOT EDIT.

package handlers

import (
	context "context"

	auth "github.com/ravilock/sentir-mais-backend/internal/auth"
	mock "github.com/stretchr/testify/mock"
)

// mockLoginer is an autogenerated mock type for the loginer type
type mockLoginer struct {
	mock.Mock
}

type mockLoginer_Expecter struct {
	mock *mock.Mock
}

func (_m *mockLoginer) EXPECT() *mockLoginer_Expecter {
	return &mockLoginer_Expecter{mock: &_m.Mock}
}

// Login provides a mock function with given fields: ctx, email, password
func (_m *mockLoginer) Login(ctx context.Context, email string, password string) (auth.Result, error) {
	ret := _m.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 auth.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (auth.Result, error)); ok {
		return rf(ctx, email, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) auth.Result); ok {
		r0 = rf(ctx, email, password)
	} else {
		r0 = ret.Get(0).(auth.Result)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockLoginer_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type mockLoginer_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
func (_e *mockLoginer_Expecter) Login(ctx interface{}, email interface{}, password interface{}) *mockLoginer_Login_Call {
	return &mockLoginer_Login_Call{Call: _e.mock.On("Login", ctx, email, password)}
}

func (_c *mockLoginer_Login_Call) Run(run func(ctx context.Context, email string, password string)) *mockLoginer_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *mockLoginer_Login_Call) Return(_a0 auth.Result, _a1 error) *mockLoginer_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockLoginer_Login_Call) RunAndReturn(run func(context.Context, string, string) (auth.Result, error)) *mockLoginer_Login_Call {
	_c.Call.Return(run)
	return _c
}

// newMockLoginer creates a new instance of mockLoginer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockLoginer(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockLoginer {
	mock := &mockLoginer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
