// Code generated by mockery v2.53.5. DO NOT EDIT.

package handlers

import (
	context "context"

	domain "github.com/ravilock/sentir-mais-backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// mockWeeklySummaryGetter is an autogenerated mock type for the weeklySummaryGetter type
type mockWeeklySummaryGetter struct {
	mock.Mock
}

type mockWeeklySummaryGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *mockWeeklySummaryGetter) EXPECT() *mockWeeklySummaryGetter_Expecter {
	return &mockWeeklySummaryGetter_Expecter{mock: &_m.Mock}
}

// GetWeek provides a mock function with given fields: ctx, userID
func (_m *mockWeeklySummaryGetter) GetWeek(ctx context.Context, userID string) domain.WeeklySummary {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetWeek")
	}

	var r0 domain.WeeklySummary
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.WeeklySummary); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(domain.WeeklySummary)
	}

	return r0
}

// mockWeeklySummaryGetter_GetWeek_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWeek'
type mockWeeklySummaryGetter_GetWeek_Call struct {
	*mock.Call
}

// GetWeek is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *mockWeeklySummaryGetter_Expecter) GetWeek(ctx interface{}, userID interface{}) *mockWeeklySummaryGetter_GetWeek_Call {
	return &mockWeeklySummaryGetter_GetWeek_Call{Call: _e.mock.On("GetWeek", ctx, userID)}
}

func (_c *mockWeeklySummaryGetter_GetWeek_Call) Run(run func(ctx context.Context, userID string)) *mockWeeklySummaryGetter_GetWeek_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *mockWeeklySummaryGetter_GetWeek_Call) Return(_a0 domain.WeeklySummary) *mockWeeklySummaryGetter_GetWeek_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockWeeklySummaryGetter_GetWeek_Call) RunAndReturn(run func(context.Context, string) domain.WeeklySummary) *mockWeeklySummaryGetter_GetWeek_Call {
	_c.Call.Return(run)
	return _c
}

// newMockWeeklySummaryGetter creates a new instance of mockWeeklySummaryGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockWeeklySummaryGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockWeeklySummaryGetter {
	mock := &mockWeeklySummaryGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
