// Code generated by mockery v2.53.5. DO NOT EDIT.

package handlers

import (
	context "context"

	domain "github.com/ravilock/sentir-mais-backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// mockMessagesLister is an autogenerated mock type for the messagesLister type
type mockMessagesLister struct {
	mock.Mock
}

type mockMessagesLister_Expecter struct {
	mock *mock.Mock
}

func (_m *mockMessagesLister) EXPECT() *mockMessagesLister_Expecter {
	return &mockMessagesLister_Expecter{mock: &_m.Mock}
}

// ListMessages provides a mock function with given fields: ctx, chatID, userID
func (_m *mockMessagesLister) ListMessages(ctx context.Context, chatID string, userID string) ([]domain.Message, error) {
	ret := _m.Called(ctx, chatID, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListMessages")
	}

	var r0 []domain.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]domain.Message, error)); ok {
		return rf(ctx, chatID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []domain.Message); ok {
		r0 = rf(ctx, chatID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, chatID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockMessagesLister_ListMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMessages'
type mockMessagesLister_ListMessages_Call struct {
	*mock.Call
}

// ListMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID string
//   - userID string
func (_e *mockMessagesLister_Expecter) ListMessages(ctx interface{}, chatID interface{}, userID interface{}) *mockMessagesLister_ListMessages_Call {
	return &mockMessagesLister_ListMessages_Call{Call: _e.mock.On("ListMessages", ctx, chatID, userID)}
}

func (_c *mockMessagesLister_ListMessages_Call) Run(run func(ctx context.Context, chatID string, userID string)) *mockMessagesLister_ListMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *mockMessagesLister_ListMessages_Call) Return(_a0 []domain.Message, _a1 error) *mockMessagesLister_ListMessages_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockMessagesLister_ListMessages_Call) RunAndReturn(run func(context.Context, string, string) ([]domain.Message, error)) *mockMessagesLister_ListMessages_Call {
	_c.Call.Return(run)
	return _c
}

// newMockMessagesLister creates a new instance of mockMessagesLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockMessagesLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockMessagesLister {
	mock := &mockMessagesLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
