// Code generated by mockery v2.53.5. DO NOT EDIT.

package handlers

import (
	context "context"

	domain "github.com/ravilock/sentir-mais-backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// mockMessageSender is an autogenerated mock type for the messageSender type
type mockMessageSender struct {
	mock.Mock
}

type mockMessageSender_Expecter struct {
	mock *mock.Mock
}

func (_m *mockMessageSender) EXPECT() *mockMessageSender_Expecter {
	return &mockMessageSender_Expecter{mock: &_m.Mock}
}

// SendMessage provides a mock function with given fields: ctx, chatID, userID, content
func (_m *mockMessageSender) SendMessage(ctx context.Context, chatID string, userID string, content string) (domain.Message, error) {
	ret := _m.Called(ctx, chatID, userID, content)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 domain.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (domain.Message, error)); ok {
		return rf(ctx, chatID, userID, content)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) domain.Message); ok {
		r0 = rf(ctx, chatID, userID, content)
	} else {
		r0 = ret.Get(0).(domain.Message)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, chatID, userID, content)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockMessageSender_SendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessage'
type mockMessageSender_SendMessage_Call struct {
	*mock.Call
}

// SendMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID string
//   - userID string
//   - content string
func (_e *mockMessageSender_Expecter) SendMessage(ctx interface{}, chatID interface{}, userID interface{}, content interface{}) *mockMessageSender_SendMessage_Call {
	return &mockMessageSender_SendMessage_Call{Call: _e.mock.On("SendMessage", ctx, chatID, userID, content)}
}

func (_c *mockMessageSender_SendMessage_Call) Run(run func(ctx context.Context, chatID string, userID string, content string)) *mockMessageSender_SendMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *mockMessageSender_SendMessage_Call) Return(_a0 domain.Message, _a1 error) *mockMessageSender_SendMessage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockMessageSender_SendMessage_Call) RunAndReturn(run func(context.Context, string, string, string) (domain.Message, error)) *mockMessageSender_SendMessage_Call {
	_c.Call.Return(run)
	return _c
}

// newMockMessageSender creates a new instance of mockMessageSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockMessageSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockMessageSender {
	mock := &mockMessageSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
