// Code generated by mockery v2.53.5. DO NOT EDIT.

package handlers

import (
	context "context"

	auth "github.com/ravilock/sentir-mais-backend/internal/auth"
	mock "github.com/stretchr/testify/mock"
)

// mockRegisterer is an autogenerated mock type for the registerer type
type mockRegisterer struct {
	mock.Mock
}

type mockRegisterer_Expecter struct {
	mock *mock.Mock
}

func (_m *mockRegisterer) EXPECT() *mockRegisterer_Expecter {
	return &mockRegisterer_Expecter{mock: &_m.Mock}
}

// Register provides a mock function with given fields: ctx, email, password
func (_m *mockRegisterer) Register(ctx context.Context, email string, password string) (auth.Result, error) {
	ret := _m.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 auth.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (auth.Result, error)); ok {
		return rf(ctx, email, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) auth.Result); ok {
		r0 = rf(ctx, email, password)
	} else {
		r0 = ret.Get(0).(auth.Result)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockRegisterer_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type mockRegisterer_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
func (_e *mockRegisterer_Expecter) Register(ctx interface{}, email interface{}, password interface{}) *mockRegisterer_Register_Call {
	return &mockRegisterer_Register_Call{Call: _e.mock.On("Register", ctx, email, password)}
}

func (_c *mockRegisterer_Register_Call) Run(run func(ctx context.Context, email string, password string)) *mockRegisterer_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *mockRegisterer_Register_Call) Return(_a0 auth.Result, _a1 error) *mockRegisterer_Register_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockRegisterer_Register_Call) RunAndReturn(run func(context.Context, string, string) (auth.Result, error)) *mockRegisterer_Register_Call {
	_c.Call.Return(run)
	return _c
}

// newMockRegisterer creates a new instance of mockRegisterer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockRegisterer(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockRegisterer {
	mock := &mockRegisterer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
