// Code generated by mockery v2.53.5. DO NOT EDIT.

package handlers

import (
	context "context"
	time "time"

	domain "github.com/ravilock/sentir-mais-backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// mockTimelineSummaryGetter is an autogenerated mock type for the timelineSummaryGetter type
type mockTimelineSummaryGetter struct {
	mock.Mock
}

type mockTimelineSummaryGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *mockTimelineSummaryGetter) EXPECT() *mockTimelineSummaryGetter_Expecter {
	return &mockTimelineSummaryGetter_Expecter{mock: &_m.Mock}
}

// GetTimeline provides a mock function with given fields: ctx, userID, from, to
func (_m *mockTimelineSummaryGetter) GetTimeline(ctx context.Context, userID string, from *time.Time, to *time.Time) (domain.DashboardTimeline, error) {
	ret := _m.Called(ctx, userID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for GetTimeline")
	}

	var r0 domain.DashboardTimeline
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *time.Time, *time.Time) (domain.DashboardTimeline, error)); ok {
		return rf(ctx, userID, from, to)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *time.Time, *time.Time) domain.DashboardTimeline); ok {
		r0 = rf(ctx, userID, from, to)
	} else {
		r0 = ret.Get(0).(domain.DashboardTimeline)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *time.Time, *time.Time) error); ok {
		r1 = rf(ctx, userID, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockTimelineSummaryGetter_GetTimeline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTimeline'
type mockTimelineSummaryGetter_GetTimeline_Call struct {
	*mock.Call
}

// GetTimeline is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - from *time.Time
//   - to *time.Time
func (_e *mockTimelineSummaryGetter_Expecter) GetTimeline(ctx interface{}, userID interface{}, from interface{}, to interface{}) *mockTimelineSummaryGetter_GetTimeline_Call {
	return &mockTimelineSummaryGetter_GetTimeline_Call{Call: _e.mock.On("GetTimeline", ctx, userID, from, to)}
}

func (_c *mockTimelineSummaryGetter_GetTimeline_Call) Run(run func(ctx context.Context, userID string, from *time.Time, to *time.Time)) *mockTimelineSummaryGetter_GetTimeline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*time.Time), args[3].(*time.Time))
	})
	return _c
}

func (_c *mockTimelineSummaryGetter_GetTimeline_Call) Return(_a0 domain.DashboardTimeline, _a1 error) *mockTimelineSummaryGetter_GetTimeline_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockTimelineSummaryGetter_GetTimeline_Call) RunAndReturn(run func(context.Context, string, *time.Time, *time.Time) (domain.DashboardTimeline, error)) *mockTimelineSummaryGetter_GetTimeline_Call {
	_c.Call.Return(run)
	return _c
}

// newMockTimelineSummaryGetter creates a new instance of mockTimelineSummaryGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockTimelineSummaryGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockTimelineSummaryGetter {
	mock := &mockTimelineSummaryGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
