// Code generated by mockery v2.53.5. DO NOT EDIT.

package services

import (
	context "context"

	domain "github.com/ravilock/sentir-mais-backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// mockUserByIDFinder is an autogenerated mock type for the userByIDFinder type
type mockUserByIDFinder struct {
	mock.Mock
}

type mockUserByIDFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *mockUserByIDFinder) EXPECT() *mockUserByIDFinder_Expecter {
	return &mockUserByIDFinder_Expecter{mock: &_m.Mock}
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *mockUserByIDFinder) FindByID(ctx context.Context, id string) (domain.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.User); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockUserByIDFinder_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type mockUserByIDFinder_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *mockUserByIDFinder_Expecter) FindByID(ctx interface{}, id interface{}) *mockUserByIDFinder_FindByID_Call {
	return &mockUserByIDFinder_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *mockUserByIDFinder_FindByID_Call) Run(run func(ctx context.Context, id string)) *mockUserByIDFinder_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *mockUserByIDFinder_FindByID_Call) Return(_a0 domain.User, _a1 error) *mockUserByIDFinder_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockUserByIDFinder_FindByID_Call) RunAndReturn(run func(context.Context, string) (domain.User, error)) *mockUserByIDFinder_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// newMockUserByIDFinder creates a new instance of mockUserByIDFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockUserByIDFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockUserByIDFinder {
	mock := &mockUserByIDFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
