// Code generated by mockery v2.53.5. DO NOT EDIT.

package services

import (
	context "context"

	domain "github.com/ravilock/sentir-mais-backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// mockUserCreator is an autogenerated mock type for the userCreator type
type mockUserCreator struct {
	mock.Mock
}

type mockUserCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *mockUserCreator) EXPECT() *mockUserCreator_Expecter {
	return &mockUserCreator_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, user
func (_m *mockUserCreator) Create(ctx context.Context, user domain.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockUserCreator_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type mockUserCreator_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - user domain.User
func (_e *mockUserCreator_Expecter) Create(ctx interface{}, user interface{}) *mockUserCreator_Create_Call {
	return &mockUserCreator_Create_Call{Call: _e.mock.On("Create", ctx, user)}
}

func (_c *mockUserCreator_Create_Call) Run(run func(ctx context.Context, user domain.User)) *mockUserCreator_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.User))
	})
	return _c
}

func (_c *mockUserCreator_Create_Call) Return(_a0 error) *mockUserCreator_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockUserCreator_Create_Call) RunAndReturn(run func(context.Context, domain.User) error) *mockUserCreator_Create_Call {
	_c.Call.Return(run)
	return _c
}

// newMockUserCreator creates a new instance of mockUserCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockUserCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockUserCreator {
	mock := &mockUserCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
