// Code generated by mockery v2.53.5. DO NOT EDIT.

package services

import (
	context "context"

	domain "github.com/ravilock/sentir-mais-backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// mockUserByEmailFinder is an autogenerated mock type for the userByEmailFinder type
type mockUserByEmailFinder struct {
	mock.Mock
}

type mockUserByEmailFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *mockUserByEmailFinder) EXPECT() *mockUserByEmailFinder_Expecter {
	return &mockUserByEmailFinder_Expecter{mock: &_m.Mock}
}

// FindByEmail provides a mock function with given fields: ctx, email
func (_m *mockUserByEmailFinder) FindByEmail(ctx context.Context, email string) (domain.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.User); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockUserByEmailFinder_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type mockUserByEmailFinder_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *mockUserByEmailFinder_Expecter) FindByEmail(ctx interface{}, email interface{}) *mockUserByEmailFinder_FindByEmail_Call {
	return &mockUserByEmailFinder_FindByEmail_Call{Call: _e.mock.On("FindByEmail", ctx, email)}
}

func (_c *mockUserByEmailFinder_FindByEmail_Call) Run(run func(ctx context.Context, email string)) *mockUserByEmailFinder_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *mockUserByEmailFinder_FindByEmail_Call) Return(_a0 domain.User, _a1 error) *mockUserByEmailFinder_FindByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockUserByEmailFinder_FindByEmail_Call) RunAndReturn(run func(context.Context, string) (domain.User, error)) *mockUserByEmailFinder_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// newMockUserByEmailFinder creates a new instance of mockUserByEmailFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockUserByEmailFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockUserByEmailFinder {
	mock := &mockUserByEmailFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
