// Code generated by mockery v2.53.5. DO NOT EDIT.

package services

import (
	context "context"

	domain "github.com/ravilock/sentir-mais-backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// mockSessionSaver is an autogenerated mock type for the sessionSaver type
type mockSessionSaver struct {
	mock.Mock
}

type mockSessionSaver_Expecter struct {
	mock *mock.Mock
}

func (_m *mockSessionSaver) EXPECT() *mockSessionSaver_Expecter {
	return &mockSessionSaver_Expecter{mock: &_m.Mock}
}

// Save provides a mock function with given fields: ctx, session
func (_m *mockSessionSaver) Save(ctx context.Context, session domain.Session) error {
	ret := _m.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Session) error); ok {
		r0 = rf(ctx, session)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockSessionSaver_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type mockSessionSaver_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - session domain.Session
func (_e *mockSessionSaver_Expecter) Save(ctx interface{}, session interface{}) *mockSessionSaver_Save_Call {
	return &mockSessionSaver_Save_Call{Call: _e.mock.On("Save", ctx, session)}
}

func (_c *mockSessionSaver_Save_Call) Run(run func(ctx context.Context, session domain.Session)) *mockSessionSaver_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Session))
	})
	return _c
}

func (_c *mockSessionSaver_Save_Call) Return(_a0 error) *mockSessionSaver_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockSessionSaver_Save_Call) RunAndReturn(run func(context.Context, domain.Session) error) *mockSessionSaver_Save_Call {
	_c.Call.Return(run)
	return _c
}

// newMockSessionSaver creates a new instance of mockSessionSaver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockSessionSaver(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockSessionSaver {
	mock := &mockSessionSaver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
