// Code generated by mockery v2.53.5. DO NOT EDIT.

package services

import (
	context "context"

	domain "github.com/ravilock/sentir-mais-backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// mockSessionByTokenFinder is an autogenerated mock type for the sessionByTokenFinder type
type mockSessionByTokenFinder struct {
	mock.Mock
}

type mockSessionByTokenFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *mockSessionByTokenFinder) EXPECT() *mockSessionByTokenFinder_Expecter {
	return &mockSessionByTokenFinder_Expecter{mock: &_m.Mock}
}

// FindByToken provides a mock function with given fields: ctx, token
func (_m *mockSessionByTokenFinder) FindByToken(ctx context.Context, token string) (domain.Session, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for FindByToken")
	}

	var r0 domain.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Session, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Session); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Get(0).(domain.Session)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockSessionByTokenFinder_FindByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByToken'
type mockSessionByTokenFinder_FindByToken_Call struct {
	*mock.Call
}

// FindByToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *mockSessionByTokenFinder_Expecter) FindByToken(ctx interface{}, token interface{}) *mockSessionByTokenFinder_FindByToken_Call {
	return &mockSessionByTokenFinder_FindByToken_Call{Call: _e.mock.On("FindByToken", ctx, token)}
}

func (_c *mockSessionByTokenFinder_FindByToken_Call) Run(run func(ctx context.Context, token string)) *mockSessionByTokenFinder_FindByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *mockSessionByTokenFinder_FindByToken_Call) Return(_a0 domain.Session, _a1 error) *mockSessionByTokenFinder_FindByToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockSessionByTokenFinder_FindByToken_Call) RunAndReturn(run func(context.Context, string) (domain.Session, error)) *mockSessionByTokenFinder_FindByToken_Call {
	_c.Call.Return(run)
	return _c
}

// newMockSessionByTokenFinder creates a new instance of mockSessionByTokenFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockSessionByTokenFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockSessionByTokenFinder {
	mock := &mockSessionByTokenFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
