// Code generated by mockery v2.53.5. DO NOT EDIT.

package middleware

import (
	context "context"

	domain "github.com/ravilock/sentir-mais-backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// mockAuthenticator is an autogenerated mock type for the authenticator type
type mockAuthenticator struct {
	mock.Mock
}

type mockAuthenticator_Expecter struct {
	mock *mock.Mock
}

func (_m *mockAuthenticator) EXPECT() *mockAuthenticator_Expecter {
	return &mockAuthenticator_Expecter{mock: &_m.Mock}
}

// Authenticate provides a mock function with given fields: ctx, token
func (_m *mockAuthenticator) Authenticate(ctx context.Context, token string) (domain.User, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.User, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.User); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockAuthenticator_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type mockAuthenticator_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *mockAuthenticator_Expecter) Authenticate(ctx interface{}, token interface{}) *mockAuthenticator_Authenticate_Call {
	return &mockAuthenticator_Authenticate_Call{Call: _e.mock.On("Authenticate", ctx, token)}
}

func (_c *mockAuthenticator_Authenticate_Call) Run(run func(ctx context.Context, token string)) *mockAuthenticator_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *mockAuthenticator_Authenticate_Call) Return(_a0 domain.User, _a1 error) *mockAuthenticator_Authenticate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockAuthenticator_Authenticate_Call) RunAndReturn(run func(context.Context, string) (domain.User, error)) *mockAuthenticator_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}

// newMockAuthenticator creates a new instance of mockAuthenticator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockAuthenticator(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockAuthenticator {
	mock := &mockAuthenticator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
