// Code generated by mockery v2.53.5. DO NOT EDIT.

package llm

import (
	context "context"

	domain "github.com/ravilock/sentir-mais-backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockSupportClient is an autogenerated mock type for the SupportClient type
type MockSupportClient struct {
	mock.Mock
}

type MockSupportClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSupportClient) EXPECT() *MockSupportClient_Expecter {
	return &MockSupportClient_Expecter{mock: &_m.Mock}
}

// GenerateReply provides a mock function with given fields: ctx, history
func (_m *MockSupportClient) GenerateReply(ctx context.Context, history []domain.Message) (string, error) {
	ret := _m.Called(ctx, history)

	if len(ret) == 0 {
		panic("no return value specified for GenerateReply")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.Message) (string, error)); ok {
		return rf(ctx, history)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []domain.Message) string); ok {
		r0 = rf(ctx, history)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []domain.Message) error); ok {
		r1 = rf(ctx, history)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSupportClient_GenerateReply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateReply'
type MockSupportClient_GenerateReply_Call struct {
	*mock.Call
}

// GenerateReply is a helper method to define mock.On call
//   - ctx context.Context
//   - history []domain.Message
func (_e *MockSupportClient_Expecter) GenerateReply(ctx interface{}, history interface{}) *MockSupportClient_GenerateReply_Call {
	return &MockSupportClient_GenerateReply_Call{Call: _e.mock.On("GenerateReply", ctx, history)}
}

func (_c *MockSupportClient_GenerateReply_Call) Run(run func(ctx context.Context, history []domain.Message)) *MockSupportClient_GenerateReply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]domain.Message))
	})
	return _c
}

func (_c *MockSupportClient_GenerateReply_Call) Return(_a0 string, _a1 error) *MockSupportClient_GenerateReply_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSupportClient_GenerateReply_Call) RunAndReturn(run func(context.Context, []domain.Message) (string, error)) *MockSupportClient_GenerateReply_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSupportClient creates a new instance of MockSupportClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSupportClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSupportClient {
	mock := &MockSupportClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
